---
collections:
  - name: https://github.com/p3ck/ansible-collections_azure.git
    type: git
    version: dev
  - name: cloud.azure_ops
    source: git+https://github.com/redhat-cop/cloud.azure_ops.git,main
    version: "5.0.0"
